-- Print current active user
SHOW USER;

-- Force Character set to LATIN9 to be compatible with Vanessa
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER SYSTEM SET AQ_TM_PROCESSES=0;
ALTER DATABASE OPEN;
ALTER DATABASE CHARACTER SET INTERNAL_USE WE8ISO8859P15;
ALTER DATABASE CHARACTER SET WE8ISO8859P15;
ALTER SYSTEM DISABLE RESTRICTED SESSION;

-- Double check character set
SELECT VALUE$ AS CHARACTER_SET
FROM SYS.PROPS$
WHERE NAME = 'NLS_CHARACTERSET';

-- Create WORKSHOPUSR tablespaces
CREATE TABLESPACE WORKSHOPUSR
DATAFILE 'WORKSHOPUSR.DAT'
SIZE 10M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE WORKSHOPUSR_TEMP
TEMPFILE 'WORKSHOPUSR_TEMP.DAT'
SIZE 5M AUTOEXTEND ON;

-- Create WORKSHOPUSR user
CREATE USER WORKSHOPUSR
IDENTIFIED BY development
DEFAULT TABLESPACE WORKSHOPUSR
TEMPORARY TABLESPACE WORKSHOPUSR_TEMP;
GRANT UNLIMITED TABLESPACE TO WORKSHOPUSR;

-- Giving WORKSHOPUSR user (all) rights
GRANT CREATE SESSION TO WORKSHOPUSR;
GRANT CREATE TABLE TO WORKSHOPUSR;
GRANT CREATE CLUSTER TO WORKSHOPUSR;
GRANT CREATE SYNONYM TO WORKSHOPUSR;
GRANT CREATE VIEW TO WORKSHOPUSR;
GRANT CREATE SEQUENCE TO WORKSHOPUSR;
GRANT CREATE DATABASE LINK TO WORKSHOPUSR;
GRANT CREATE PUBLIC DATABASE LINK TO WORKSHOPUSR;
GRANT CREATE PROCEDURE TO WORKSHOPUSR;
GRANT CREATE TRIGGER TO WORKSHOPUSR;
GRANT CREATE MATERIALIZED VIEW TO WORKSHOPUSR;
GRANT CREATE TYPE TO WORKSHOPUSR;
GRANT CREATE OPERATOR TO WORKSHOPUSR;
GRANT CREATE INDEXTYPE TO WORKSHOPUSR;
GRANT CREATE DIMENSION TO WORKSHOPUSR;
GRANT CREATE ANY CONTEXT TO WORKSHOPUSR;
GRANT CREATE JOB TO WORKSHOPUSR;
