CONN WORKSHOPUSR/development;

set sqlblanklines on

-- Print current active user
SHOW USER;

CREATE TABLE VAN_WORKSHOP (
	WORKSHOPID           NUMBER(*, 0) NOT NULL,
	WORKSHOPMESSAGE VARCHAR2(200 BYTE),
	CONSTRAINT PK_VAN_WORKSHOP PRIMARY KEY (WORKSHOPID)
);

CREATE SEQUENCE SEQ_VAN_WORKSHOPID NOCACHE;

CREATE OR REPLACE TRIGGER TIB_VAN_WORKSHOP
BEFORE INSERT
	ON VAN_WORKSHOP
FOR EACH ROW
	BEGIN
		--  Column "WORKSHOPID" uses sequence SEQ_VAN_WORKSHOPID
		SELECT SEQ_VAN_WORKSHOPID.NEXTVAL
		INTO :NEW.WORKSHOPID
		FROM DUAL;
    END;
/
